//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string NomUsuario { get; set; }
        public string Mail { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string NomCompleto { get; set; }
        public string Contraseña { get; set; }
    }
}
